# Generated by Django 2.0 on 2018-06-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(choices=[('SOFAS & LOUNGERS', 'SOFAS & LOUNGERS'), ('SETTEES & BENCHES', 'SETTEES & BENCHES'), ('ACCENT CHAIRS', 'ACCENT CHAIRS'), ('FOLDING CHAIRS', 'FOLDING CHAIRS'), ('PLASTIC CHAIRS', 'PLASTIC CHAIRS'), ('STOOLS', 'STOOLS'), ('BEAN BAGS', 'BEAN BAGS'), ('TV UNITS', 'TV UNITS'), ('DISPLAY UNITS', 'DISPLAY UNITS'), ('CABINETS', 'CABINETS'), ('SHOE RACKS', 'SHOE RACKS'), ('COFFEE TABLES', 'COFFEE TABLES'), ('END TABLES', 'END TABLES'), ('CONSOLE TABLES', 'CONSOLE TABLES'), ('DINING', 'DINING'), ('MODULAR KITCHEN', 'MODULAR KITCHEN'), ('BAR FURNITURE', 'BAR FURNITURE'), ('BEDS', 'BEDS'), ('MATTRESSES', 'MATTRESSES'), ('BEDSIDE TABLES', 'BEDSIDE TABLES'), ('CHEST OF DRAWERS', 'CHEST OF DRAWERS'), ('DRESSING TABLES', 'DRESSING TABLES'), ('WARDROBES', 'WARDROBES'), ('MODULAR WARDROBES', 'MODULAR WARDROBES'), ('KIDS FURNITURE', 'KIDS FURNITURE'), ('STUDY TABLES', 'STUDY TABLES'), ('BOOK SHELVES', 'BOOK SHELVES'), ('BOOK CASES', 'BOOK CASES'), ('FURNITURE ACCENTS', 'FURNITURE ACCENTS'), ('OFFICE FURNITURE', 'OFFICE FURNITURE'), ('OUTDOOR FURNITURE', 'OUTDOOR FURNITURE')], default='SHOE RACKS'),
            preserve_default=False,
        ),
    ]
