# Generated by Django 2.0 on 2018-06-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='product',
            field=models.ManyToManyField(to='Store.Product'),
        ),
    ]
