# Generated by Django 2.0 on 2018-06-13 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_contact_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='product',
        ),
        migrations.AddField(
            model_name='contact',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Store.Product'),
            preserve_default=False,
        ),
    ]
