# Generated by Django 2.0 on 2018-06-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_auto_20180613_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.Product'),
        ),
    ]
